config/routes.rb
KitchenStadium::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "allergies/create"

  match '/login', to: "sessions#create", as: 'login'
  match '/logout', to: "sessions#destroy", as: 'logout', via: :delete
  match '/mail', to: "users#mailchimp"
  resources :users do
    member do
      get :edit_allergies
      post :set_allergies
      get :edit_diet
      post :set_diet
      get :edit_food
      post :set_food
      get :edit_tastes
      post :set_tastes
    end
  end

  get "site/home"

  root to: "site#home"

  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email,
  						:full_name,
  						:zip,
  						:remember_token,
  						:password,
  						:password_confirmation,
              :is_vegan,
              :likes_desserts,
              :eating_habits,
              :spicy_preference,
              :registration_page,
              :other_allergies

  before_create :create_token
  before_save { |user| user.email.downcase! }

  has_many :user_allergies
  has_many :allergies, through: :user_allergies

  has_many :user_diets
  has_many :diets, through: :user_diets

  has_many :user_foods
  has_many :foods, through: :user_foods

  has_many :user_food_types
  has_many :food_types, through: :user_food_types

  validates :full_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX }

  def has_allergy
    if self.allergies.count > 0
      true
    else
      false
    end
  end

  def registration_page
    if self[:registration_page]
      return [5, self[:registration_page]].min
    else
      0
    end
  end

  def registration_completed
    if self[:registration_page].present? && self[:registration_page] > 4
      return true
    else
      return false
    end
  end

  def allergy_str
    self.allergies.map do |a|
      a.name
    end.join(", ")
  end

  def fav_foods_str
    self.user_foods.where(frequency: 'often').map do |f|
      f.food.name
    end.join(", ")
  end

  def fav_food_types_str
    self.user_food_types.where(frequency: 'often').map do |f|
      f.food_type.name
    end.join(", ")
  end

  def diets_str
    self.diets.map do |a|
      a.name
    end.join(", ")
  end

  private
  	def create_token
  		self.remember_token = SecureRandom.urlsafe_base64
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
  	@user = User.new(params[:user])
    @user.is_vegan = false
    @user.likes_desserts = true
    @user.spicy_preference = "medium"
    @user.registration_page = 1
  	if @user.save
      Notifier.register(@user).deliver
      subscribe(@user)
      login(@user)
  		redirect_to edit_allergies_user_path(@user)
  	else
      flash[:error] = @user.errors.full_messages
  		redirect_to root_url
  	end
  end

  def edit_allergies
  	@allergies = Allergy.featured
  	@user = User.find(params[:id])
    @step = 1
  end

  def set_allergies
    @mixpanel.track "First Page"
    @user = User.find(params[:id])
    @user.registration_page = @user.registration_page+1
    if params[:other_allergy_name].present?
      @user.other_allergies = params[:other_allergy_name]
    end
    @user.save
    @user.user_allergies.each do |allergy|
      allergy.destroy
    end
    if params[:has_allergy] == 'true'
      unless params[:allergy_ids].nil?
        params[:allergy_ids].each do |id|
          @user.allergies << Allergy.find(id)
        end
      end
    end
    redirect_to edit_diet_user_path(@user)
  end

  def edit_diet
    @user = User.find(params[:id])
    @step = 2
  end

  def set_diet
    @mixpanel.track "Second Page"
    @user = User.find(params[:id])
    @user.update_attributes(is_vegan: params[:is_vegan], registration_page: @user.registration_page+1)
    Diet.featured.each do |diet|
      frequency = params[diet.name]
      unless frequency.nil?
        if user_diet = @user.user_diets.where(diet_id: diet.id).first
          user_diet.update_attributes(frequency: frequency)
        else
          UserDiet.create(user_id: @user.id,
                          diet_id: diet.id,
                          frequency: frequency)
        end    
      end
    end
    @user.user_diets.each do |diet|
      if diet.diet.is_special == true
        diet.destroy
      end
    end
    unless params[:sp_diet_ids].nil?
      params[:sp_diet_ids].each do |id|
        @user.diets << Diet.find(id)
      end
    end
    redirect_to edit_food_user_path(@user)
  end

  def edit_food
    @user = User.find(params[:id])
    @step = 3
  end

  def set_food
    @mixpanel.track "Third Page"
    @user = User.find(params[:id])
    @user.update_attributes(registration_page: @user.registration_page+1)
    Food.all.each do |food|
      frequency = params[food.name]
      unless frequency.nil?
        if user_food = @user.user_foods.where(food_id: food.id).first
          user_food.update_attributes(frequency: frequency)
        else
          UserFood.create(user_id: params[:id],
                          food_id: food.id,
                          frequency: frequency)    
        end
      end
    end
    FoodType.all.each do |foodtype|
      frequency = params[foodtype.name]
      unless frequency.nil?
        if user_food_type = @user.user_food_types.where(food_type_id: foodtype.id).first
          user_food_type.update_attributes(frequency: frequency)
        else
          UserFoodType.create(user_id: params[:id],
                        food_type_id: foodtype.id,
                        frequency: frequency)  
        end  
      end
    end
    redirect_to edit_tastes_user_path(User.find(params[:id]))
  end

  def edit_tastes
    @user = User.find(params[:id])
    @step = 4
  end

  def set_tastes
    @mixpanel.track "Fourth Page"
    @user = User.find(params[:id])
    @user.update_attributes(spicy_preference: params[:spicy_preference],
                            likes_desserts: params[:likes_desserts],
                            eating_habits: params[:eating_habits],
                            registration_page: @user.registration_page+1)
    # intercom_custom_data.user[:app_activated_at] = Time.now
    # intercom_custom_data.user[:spicy_preference] = params[:spicy_preference]
    # intercom_custom_data.user[:likes_desserts] = params[:likes_desserts]
    # intercom_custom_data.user[:eating_habits] = params[:eating_habits]
    # intercom_custom_data.user[:registration_page] = @user.registration_page
    flash[:success] = "Thank you for your time! We will be in touch."
    redirect_to root_url
  end

  def finish
    @user = User.find(params[:id])
  end

  def mailchimp
    @lists = Gibbon::API.lists.list({:filters => {:list_name => "Kitchen Stadium Subscribers"}})
    list_id = @lists["data"].first["id"]
    Gibbon::API.lists.subscribe({:id => list_id, :email => {:email => 'billy@hackathon.io'}, :double_optin => false})
  end

  private
    def subscribe(user)
      @lists = Gibbon::API.lists.list({:filters => {:list_name => "Kitchen Stadium Subscribers"}})
      list_id = @lists["data"].first["id"]
      name = @user.full_name.split(' ')
      first = name.shift
      last = name.join(' ')
      Gibbon::API.lists.subscribe({:id => list_id, 
                                :email => {:email => @user.email}, 
                           :merge_vars => {:FNAME => first, :LNAME => last},
                         :double_optin => false})
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def diet_val(user, diet, frequency)
		if user.diets.count == 0  || !(user_diet = user.user_diets.where(diet_id: diet.id).first)
		# 	if frequency == 'never'
		# 		return true
		# 	else 
		# 		return false
		# 	end
			return false
		end
		return user_diet.frequency == frequency
	end

	def food_val(user, food, frequency)
		if user.foods.count == 0 || !(user_food = user.user_foods.where(food_id: food.id).first)
		# 	if frequency == 'never'
		# 		return true
		# 	else 
				return false
		# 	end
		end
		return user_food.frequency == frequency
	end

	def food_type_val(user, food_type, frequency)
		if user.food_types.count == 0 || !(user_food_type = user.user_food_types.where(food_type_id: food_type.id).first)
		# 	if frequency == 'never'
		# 		return true
		# 	else 
		 		return false
		# 	end
		end
		return user_food_type.frequency == frequency
	end

	def spicy_val(user, val)
		return user.spicy_preference == val
	end
	def dessert_val(user, val)
		return user.likes_desserts == val
	end
end

app/views/users/edit_allergies.html.haml
.row-fluid
  .span12
    .align-center68
      = render "shared/form_header"
      = form_tag set_allergies_user_path(@user), method: :post, id: "allergy-form" do
        .row-fluid
          .span9
            #has-allergy-box.form-field
              .span4
                DO YOU HAVE ANY FOOD ALLERGIES?
                %span.required-dot *
              .span8
                .box
                  = radio_button_tag 'has_allergy', false, !@user.has_allergy, { :onclick => "$('#allergy-types').hide();" }
                  NO
                .box
                  = radio_button_tag 'has_allergy', true, @user.has_allergy, { :onclick => "$('#allergy-types').show(); $('#has-allergy-box').addClass('selected');"}
                  YES
        .row-fluid
          .span9
            #allergy-types.form-field{style: ("display:block;" if @user.has_allergy)}
              .span4
                Are you allergic to
              .span8
                - Allergy.featured.each do |allergy|
                  .check-box
                    = check_box_tag 'allergy_ids[]', allergy.id, @user.allergies.include?(allergy), {:onclick =>  "$('#allergy-types').addClass('selected')" }
                    = allergy.name
                .check-box
                  = check_box_tag 'other_allergy', true, !@user.other_allergies.nil?, { :onclick => "$('#other-allergy-box').show(); $('#allergy-types').addClass('selected')"}
                  Other
        .row-fluid
          .span9
            #other-allergy-box.form-field{style: ("display:block;" unless @user.other_allergies.nil?)}
              .span4
                What are you allergic to?
              .span8
                = text_field_tag 'other_allergy_name', @user.other_allergies, placeholder: 'Type Allergies Here'

        .row-fluid
          .span7
            = submit_tag "Save Allergy Information", class: "submit-btn btn"
          .span5
            .page-number
              = "#{@step}/4"

app/views/users/edit_diet.html.haml
.row-fluid
  .span12
    .align-center68
      = render "shared/form_header"
      = form_tag set_diet_user_path(@user), method: :post, id: "diet-form" do
        .row-fluid
          .span9
            #has-allergy-box.form-field
              .span4
                Are you a vegetarian?
              .span8
                .box
                  = radio_button_tag 'is_vegan', false, !@user.is_vegan, { :onclick => "$('.not-vegan').show();" }
                  NO
                .box
                  = radio_button_tag 'is_vegan', true, @user.is_vegan, { :onclick => "$('.not-vegan').hide(); $('#has-allergy-box').addClass('selected');"}
                  YES
        .row-fluid
          #diet-types
            HOW OFTEN DO YOU EAT
            %table
              %tr{style: "background-color:#E6E6E6;"}
                %th 
                %th Never
                %th Sometimes
                %th Often
              - Diet.featured.each do |diet|
                %tr{class: "#{('not-vegan' if diet.is_vegan == false)}  #{cycle('odd', 'even')}", style: ("display:none;" if @user.is_vegan == true && diet.is_vegan == false)}
                  %td
                    = diet.name
                  %td
                    = radio_button_tag diet.name, 'never', diet_val(@user, diet, 'never'), { :onclick => ""}
                  %td
                    = radio_button_tag diet.name, 'sometimes', diet_val(@user, diet, 'sometimes'), { :onclick => ""}
                  %td
                    = radio_button_tag diet.name, 'often', diet_val(@user, diet, 'often'), { :onclick => ""}
        .row-fluid
          #special-types.form-field
            .span4
              ANY SPECIAL DIET THAT YOU ARE ON?
            .span8
              - Diet.special.each do |diet|
                .check-box
                  = check_box_tag 'sp_diet_ids[]', diet.id, @user.diets.include?(diet), {:onclick =>  "$('#special-types').addClass('selected')" }
                  = diet.name
        .row-fluid
          .span7
            = link_to "Previous", edit_allergies_user_path(@user), class: "prev-link"
            = submit_tag "Save Dietary Information", class: "submit-btn btn"
          .span5
            .page-number
              = "#{@step}/4"

app/views/users/edit_food.html.haml
.row-fluid
  .span12
    .align-center68
      = render "shared/form_header"
      = form_tag set_food_user_path(@user), method: :post, id: "diet-form" do
        .row-fluid
          #diet-types
            HOW OFTEN DO YOU PREFER?
            %table
              %tr
                %th 
                %th Never
                %th Sometimes
                %th Often
              - Food.all.each do |food|
                %tr{class: "#{cycle('odd', 'even')}"}
                  %td
                    = food.name
                  %td
                    = radio_button_tag food.name, 'never', food_val(@user, food, 'never'), { :onclick => ""}
                  %td
                    = radio_button_tag food.name, 'sometimes', food_val(@user, food, 'sometimes'), { :onclick => ""}
                  %td
                    = radio_button_tag food.name, 'often', food_val(@user, food, 'often'), { :onclick => ""}
        .row-fluid
          #diet-types
            HOW OFTEN DO YOU ORDER OR COOK?
            %table
              %tr
                %th 
                %th Never
                %th Sometimes
                %th Often
              - FoodType.all.each do |foodtype|
                %tr{class: "#{cycle('odd', 'even')}"}
                  %td
                    = foodtype.name
                  %td
                    = radio_button_tag foodtype.name, 'never', food_type_val(@user, foodtype, 'never'), { :onclick => ""}
                  %td
                    = radio_button_tag foodtype.name, 'sometimes', food_type_val(@user, foodtype, 'sometimes'), { :onclick => ""}
                  %td
                    = radio_button_tag foodtype.name, 'often', food_type_val(@user, foodtype, 'often'), { :onclick => ""}
        .row-fluid
          .span7
            = link_to "Previous", edit_diet_user_path(@user), class: "prev-link"
            = submit_tag "Save Favorite Cuisines", class: "submit-btn btn"
          .span5
            .page-number
              = "#{@step}/4"

app/views/users/edit_tastes.html.haml
.row-fluid
  .span12
    .align-center68
      = render "shared/form_header"
      = form_tag set_tastes_user_path(@user), method: :post, id: "allergy-form" do
        .row-fluid.form-field
          .span9
            .span5
              HOW DO YOU LIKE YOUR FOOD?
            .span7
              .radio-box
                = radio_button_tag 'spicy_preference', 'mild', spicy_val(@user, 'mild')
                Mild
              .radio-box
                = radio_button_tag 'spicy_preference', 'medium', spicy_val(@user, 'medium')
                Medium
              .radio-box
                = radio_button_tag 'spicy_preference', 'spicy', spicy_val(@user, 'spicy')
                Spicy
        .row-fluid.form-field
          .span9
            .span5
              DO YOU LIKE DESSERTS?
            .span7
              .box
                = radio_button_tag 'likes_desserts', 1, dessert_val(@user, 1)
                Oh yeah
              .box
                = radio_button_tag 'likes_desserts', 0, dessert_val(@user, 0)
                Nope, don't like sweets or desserts
        .row-fluid.form-field
          .span9
            .span5
              Anything else you would like to to tell us about your food habits?
            .span7
              = text_area_tag 'eating_habits', @user.eating_habits, class: "big-text-area"
        .row-fluid
          .span7
            = link_to "Previous", edit_food_user_path(@user), class: "prev-link"
            = submit_tag "Submit", class: "submit-btn btn"
          .span5
            .page-number
              = "#{@step}/4"